Repository sharpbrick/powered-up, pull requests merged in 2021-04, with the labels that each got.

#159 Fix Analyzer Warnings
  examples/SharpBrick.PoweredUp.Examples/ExampleTwoHubsMotorControl.cs
  src/SharpBrick.PoweredUp.BlueGigaBLE/BlueGigaBLEPoweredUpBluetoothAdapater.cs
  src/SharpBrick.PoweredUp.BlueGigaBLE/ServiceCollectionExtensionsForBlueGigaBLE.cs
  src/SharpBrick.PoweredUp.Mobile/XamarinPoweredUpBluetoothCharacteristic.cs
  src/SharpBrick.PoweredUp.WinRT/WinRTPoweredUpBluetoothDevice.cs
  src/SharpBrick.PoweredUp.WinRT/WinRTPoweredUpBluetoothService.cs
Labels: code-quality

#168 TechnicMotor TestScript (on master)
  powered-up.sln
  src/SharpBrick.PoweredUp/Deployment/HubExtensions.cs
  src/SharpBrick.PoweredUp/PoweredUpHost.cs
  test/SharpBrick.PoweredUp.TestScript/ITestScript.cs
  test/SharpBrick.PoweredUp.TestScript/Program.cs
  test/SharpBrick.PoweredUp.TestScript/SharpBrick.PoweredUp.TestScript.csproj
  test/SharpBrick.PoweredUp.TestScript/TechnicMotorTestScript.cs
  test/SharpBrick.PoweredUp.TestScript/TestScriptExecutionContext.cs
Labels: code-quality

#167 155-BlueGiga-documentation
  README.md
  docs/bleadapters/BlueGigaBLED112.md
Labels: area-bt-bluegiga, documentation

#166 Issue 165 examples simplification
  examples/SharpBrick.PoweredUp.Examples/Program.cs
Labels: area-bt-bluegiga, area-bt-winrt, code-quality, enhancement

#169 Add MindstormsSensors TestScript
  examples/SharpBrick.PoweredUp.Examples/ExampleTechnicDistanceSensor.cs
  src/SharpBrick.PoweredUp/Devices/TechnicDistanceSensor.cs
  test/SharpBrick.PoweredUp.TestScript/Program.cs
  test/SharpBrick.PoweredUp.TestScript/Scripts/MindstormsSensorsTestScript.cs
  test/SharpBrick.PoweredUp.TestScript/Scripts/TechnicMotorTestScript.cs
Labels: area-devices, code-quality, enhancement

#160 Add Option to decode SI/PCT to Double instead of using Raw DataType
  examples/SharpBrick.PoweredUp.Examples/ExampleDynamicDevice.cs
  src/SharpBrick.PoweredUp/Devices/AbsoluteMotor.cs
  src/SharpBrick.PoweredUp/Devices/BasicMotor.cs
  src/SharpBrick.PoweredUp/Devices/ColorDistanceSensor.cs
  src/SharpBrick.PoweredUp/Devices/Current.cs
  src/SharpBrick.PoweredUp/Devices/Device.cs
  src/SharpBrick.PoweredUp/Devices/DuploTrainBaseColorSensor.cs
  src/SharpBrick.PoweredUp/Devices/DuploTrainBaseMotor.cs
  src/SharpBrick.PoweredUp/Devices/DuploTrainBaseSpeaker.cs
  src/SharpBrick.PoweredUp/Devices/DuploTrainBaseSpeedometer.cs
  src/SharpBrick.PoweredUp/Devices/MarioHubAccelerometer.cs
  src/SharpBrick.PoweredUp/Devices/MarioHubPants.cs
  src/SharpBrick.PoweredUp/Devices/MarioHubTagSensor.cs
  src/SharpBrick.PoweredUp/Devices/Mode.cs
  src/SharpBrick.PoweredUp/Devices/MoveHubTiltSensor.cs
  src/SharpBrick.PoweredUp/Devices/MultiValueMode.cs
  src/SharpBrick.PoweredUp/Devices/RemoteControlButton.cs
  src/SharpBrick.PoweredUp/Devices/RemoteControlRssi.cs
  src/SharpBrick.PoweredUp/Devices/SingleValueMode.cs
  src/SharpBrick.PoweredUp/Devices/TachoMotor.cs
  src/SharpBrick.PoweredUp/Devices/TechnicColorSensor.cs
  src/SharpBrick.PoweredUp/Devices/TechnicDistanceSensor.cs
  src/SharpBrick.PoweredUp/Devices/TechnicMediumHubAccelerometer.cs
  src/SharpBrick.PoweredUp/Devices/TechnicMediumHubGestSensor.cs
  src/SharpBrick.PoweredUp/Devices/TechnicMediumHubGyroSensor.cs
  src/SharpBrick.PoweredUp/Devices/TechnicMediumHubTemperatureSensor.cs
  src/SharpBrick.PoweredUp/Devices/TechnicMediumHubTiltSensor.cs
  src/SharpBrick.PoweredUp/Devices/Value.cs
  src/SharpBrick.PoweredUp/Devices/Voltage.cs
  src/SharpBrick.PoweredUp/Protocol/Formatter/PortValueSingleEncoder.cs
  src/SharpBrick.PoweredUp/Protocol/Knowledge/PortModeInfo.cs
  src/SharpBrick.PoweredUp/Protocol/Messages/MessageOfPortValuesModel.cs
  src/SharpBrick.PoweredUp/Protocol/Messages/PortValueData.cs
  test/SharpBrick.PoweredUp.Test/Protocol/Formatter/PortValueCombinedModeEncoderTest.cs
  test/SharpBrick.PoweredUp.Test/Protocol/Formatter/PortValueEncoderTest.cs
Labels: area-devices, area-messages, breaking-change, bug

#175 Updated Mario Pants
  src/SharpBrick.PoweredUp/Enums/MarioPants.cs
Labels: enhancement
