Repository sharpbrick/powered-up, pull requests merged in 2024-02, with the labels that each got.

#185 Add README file
  Directory.Build.props
  src/SharpBrick.PoweredUp/SharpBrick.PoweredUp.csproj
Labels: enhancement

#202 Add Protocol Only Example
  .vscode/launch.json
  README.md
  examples/SharpBrick.PoweredUp.ExampplesOnProtocol/Program.cs
  examples/SharpBrick.PoweredUp.ExampplesOnProtocol/SharpBrick.PoweredUp.ExampplesOnProtocol.csproj
  powered-up.sln
Labels: documentation

#197 Added new static port information for TechnicLargeLinearMotor
  src/SharpBrick.PoweredUp/Devices/TechnicLargeLinearMotor.cs
  src/SharpBrick.PoweredUp/Devices/TechnicMediumAngularMotorGrey.cs
  src/SharpBrick.PoweredUp/Devices/TechnicXLargeLinearMotor.cs
Labels: enhancement, area-device-motor
